#!/usr/bin/env bash
if [[ $# -eq 1 ]]; then
	file_found=0
	for p in $(fip -pu); do
		file="${p}/$1"
		[[ -e "$file" ]] && { file_found=1; break; }
	done

	if [[ "$file_found" == 1 ]]; then
		vim "$file"
	else
		wait_user_input=1
		until [[ $wait_user_input == 0 ]]; do
			printf "Did not found \"%s\", do you want to create it? (y/N) " "$file" >&2
			read -r -N 1 ans
			case $ans in
				y|Y)
					wait_user_input=0
					printf "\n" >&2
					# todo: provides the path of file being created
					touch "$file"
					chmod u+x "$file"
					vim "$file"
					;;
				n|N)
					wait_user_input=0
					printf "\n" >&2
					;;
				*)
					printf "\nInvalid input, please retry.\n" >&2
					;;
			esac
		done
	fi
fi

